### ISSUE TITLE
Please rename your repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [Skylifee7/Mafia-TCoS-CS319-Group2A#1]
to include your course and group number

**Comment by gokcan** [comment]
Course code and group number have been appended to the repo name. 👍

**Comment by ugurdogrusoz** [comment]
Thanks! Next time you should assign the issue to the person who created it instead of directly closing it. They should verify and close :)

**Comment by gokcan** [comment]
Understood sir :)
