### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by metincansiper** [Skylifee7/Mafia-TCoS-CS319-Group2A#10]
Hi guys,
I am looking at your codes. I realized that in the root you have 3 folders "Mafia-TCoS-source", "Mafia-TCos Source" and "Src". 

I need to know about what are the main functionality of the code located inside each of these 3 folders. Especially the names "Mafia-TCoS-source" and "Mafia-TCos Source" are realy close to each other, they are seperated by just one letter and this seems confusing to me.  

Would you provide me with an answer latest tomorrow morning? (I appraciate if you provide a quick answer)

Thanks,
Metin

**Comment by gokcan** [comment]
**Hi sir,** @metincansiper 
We had experienced merge conflicts. So, after I merged my branch(Gokcan-feature-branch) with the master;  Melis and Gökberk merged their branches too(with changing the file names.)

This below branch is the branch contains the **Main.java**, _Network, Server(Node.js), Controller_ subsystems and some of the UI and Model classes https://github.com/Skylifee7/Mafia-TCoS-CS319-Group2A/tree/master/Mafia-TCoS-source.

Melis' and Gökberk's branches contain some of the UI and Model classes which you may want to see from below links:
https://github.com/Skylifee7/Mafia-TCoS-CS319-Group2A/tree/master/Mafia-TCos%20Source
https://github.com/Skylifee7/Mafia-TCoS-CS319-Group2A/tree/master/Src

Regards.
-Gökcan
