### ISSUE TITLE
Are you sure you want to do a "text" based game?

### ISSUE THREAD

**Issue by ugurdogrusoz** [Skylifee7/Mafia-TCoS-CS319-Group2A#2]
As I tried to emphasize in class, even though any kind of automation / computing can be performed with object-oriented software, as an educational project, one with a graphical UI, rich set of objects, and lots of interaction on the screen is a more suitable project.

**Comment by gokberkaktulay** [comment]
Yes.

**Comment by gokcan** [comment]
**Hi sir,** @ugurdogrusoz 

Our game, _Mafia:TCoS_, has been discussed and designed as similar to [Omerta](https://omerta.com.tr) but with not "Massive-Multiplayer" and "browser-based" properties, rather it is a Desktop Client of the original game. [More info about Omerta (https://en.wikipedia.org/wiki/Omerta_(video_game))

Mafia:The City of Sin players would rank up by stealing cars, committing crimes, dealing and producing narcotics. Other than that, our game will have a **rich and clean graphical UI**, **database-connectivity**, **map** and **complex "stats"** calculations on backend. 

Our pre-Alpha mockup of the game has been designed today(21 Feb) and we decided to discuss those mockups with you on the 22 Feb's class, sir.

Thanks for your interest!
Regards.
_-Gökcan_
